const feedbacklist = [
  {
    id: 1,
    name: "Aarav",
    anon: false,
    rating: 8,
    tags: ["UI", "Performance"],
    msg: "The new design looks amazing, but the dashboard could load faster on mobile.",
    ts: Date.now() - 86400000 * 2,
    like: 5,
    love: 3,
    dislike: 0,
    reply: "",
  },
  {
    id: 2,
    name: "Mira",
    anon: true,
    rating: 10,
    tags: ["Performance", "Praise"],
    msg: "Super fast now! Animations are silky smooth. Keep it up 🙌",
    ts: Date.now() - 86400000 * 1.5,
    like: 8,
    love: 6,
    dislike: 0,
    reply: "Thanks for the love!",
  },
  {
    id: 3,
    name: "Dev",
    anon: false,
    rating: 6,
    tags: ["Features"],
    msg: "Would love multi-project support and bulk tagging.",
    ts: Date.now() - 86400000 * 0.8,
    like: 2,
    love: 1,
    dislike: 0,
    reply: "",
  },
  {
    id: 4,
    name: "Sara",
    anon: false,
    rating: 4,
    tags: ["Bug", "UX"],
    msg: "Ran into a bug while saving. Also the settings labels are a bit confusing.",
    ts: Date.now() - 86400000 * 0.3,
    like: 1,
    love: 0,
    dislike: 2,
    reply: "",
  },
];
export default feedbacklist;
